# -*- coding: utf-8 -*-
"""DetectarPalavras.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HpqbhRls9F_Hp04q1i12Yg7l2I_YKPZM
"""

def encontrar_palavras_suspeitas(email_texto):

  phishing_elements = [
      # 1. Urgency and Threat
      "Action Required",
      "Immediate attention required",
      "Urgent",
      "Act now",
      "Your account will be suspended",
      "Your account will be closed",
      "Failure to comply",
      "Security alert",
      "Warning",
      "Time-sensitive",
      "Expires soon",
      "Last chance",
      "Critical update",
      "Compromised account",
      "Unauthorized activity detected",
      "Your access will be terminated",
      "Verify your account immediately",

      # 2. Impersonation and Authority
      "Official notification",
      "Security department",
      "Customer support",
      "Billing department",
      "IT support",
      "Admin",
      "Service desk",
      "Compliance",
      "Legal department",
      "Invoice",
      "Payment",
      "Refund",
      "Delivery",
      "Tax",
      "Government",
      "Bank",
      "Credit card",
      "PayPal",
      "Amazon",
      "Netflix",
      "Microsoft",
      "Apple",

      # 3. Financial and Account Issues
      "Transaction failed",
      "Payment pending",
      "Unusual activity",
      "Suspicious login",
      "Account locked",
      "Password reset",
      "Update billing information",
      "Verify payment details",
      "Debit/Credit",
      "Balance",
      "Overdue",
      "Invoice attached",
      "Wire transfer",
      "Funds",
      "Limited access",
      "Frozen account",

      # 4. Call to Action
      "Click here",
      "Verify your account",
      "Update your information",
      "Log in to your account",
      "Confirm your details",
      "Download attachment",
      "Review the document",
      "Unblock your account",
      "Access your secure message",
      "Follow this link",
      "Respond to this email",
      "Complete the form",

      # 5. Personal Information Requests
      "Social Security Number",
      "Date of birth",
      "Mother's maiden name",
      "Credit card number",
      "Bank account details",
      "PIN",
      "Security questions/answers",
      "Full name",
      "Address",
      "Phone number",
      "Username",
      "Password",

      # 6. Generic Greetings and Closings
      "Dear Customer",
      "Dear User",
      "Dear Valued Client",
      "Sincerely",
      "Regards",
      "Thank you",
      "The Team",
      "Customer Support",
      "Account Services",
      "Security Department",

      # 7. Technical/Security Jargon (Misused or Out of Context)
      "SSL certificate",
      "Encryption",
      "IP address",
      "Server error",
      "Data breach",
      "Firewall",
      "Malware",
      "Phishing attempt",
      "Two-factor authentication",
      "Protocol",
      "Domain",
      "Proxy"
  ]
  
  x=0
  texto_normalizado = email_texto.lower()
  encontradas = []
  for palavra in phishing_elements:
    if palavra.lower() in texto_normalizado:
      encontradas.append(palavra)
      x+=1
  if x>0 and x<=3:
    return 0.1
  elif x>3 and x<5:
    return 0.25
  elif x>=5:
    return 0.4
  return 0

email = """"""
print(encontrar_palavras_suspeitas(email))